var startlist = [
    {id: 1, name: 'OLAFIT'},
    {id: 2, name: 'Vopraváři'},
    {id: 3, name: 'Triezvych nas nedostanu'},
    {id: 4, name: 'Beerturisti'},
    {id: 5, name: 'Dneska s Mírou'},
    {id: 6, name: 'Wish you were bear'},
    {id: 7, name: 'Duo MORDOR'},
    {id: 8, name: 'Pejsek a kočička'},
    {id: 9, name: 'Pacienti'},
    {id: 10, name: 'Burani'},
    {id: 11, name: 'Flamingo Brothers'},
    {id: 12, name: 'Klub chovatelů ptactva'},
    {id: 13, name: 'Kobry!'},
    {id: 14, name: 'Bezdůstojní'},
    {id: 15, name: 'Autcideři'},
    {id: 16, name: 'Počůráníčko'},
    {id: 17, name: 'Užovky'},
    {id: 18, name: 'Krčok jaternice'},
    {id: 19, name: 'Lenochodi'},
    {id: 20, name: 'Bez Píva to nejde'},
    {id: 21, name: 'BloodBrothers'},
    {id: 22, name: 'Čubičky'},
    {id: 23, name: ''},
    {id: 24, name: ''},
    {id: 25, name: ''},
    {id: 26, name: ''},
    {id: 27, name: ''},
    {id: 28, name: ''},
    {id: 29, name: ''},
]